import { Pressable, ScrollView, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { IconSymbol } from '@/components/ui/icon-symbol';

export default function LegalScreen() {
  const params = useLocalSearchParams<{ section?: string }>();
  const showTerms = params.section === 'terms';
  return <ScreenContainer className="bg-background" safeAreaClassName="bg-background"><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 42 }}><Pressable onPress={() => router.back()} className="mb-6 flex-row items-center"><IconSymbol name="chevron.left" size={20} color="#2D5A27" /><Text className="ml-2 font-body text-sm font-bold text-primary">Kembali</Text></Pressable><Text className="font-body text-xs font-bold uppercase tracking-widest text-primary">OR.TRIP ADVENTURE</Text><Text className="mt-2 font-heading text-3xl font-bold leading-9 text-foreground">Informasi legal</Text><Text className="mt-2 font-body text-sm leading-6 text-muted">Dokumen ringkas untuk membantu kamu memahami penggunaan layanan dan proses booking Or.Trip Adventure.</Text><View className="mt-6 flex-row rounded-2xl bg-neutral p-1"><LegalTab label="Privacy Policy" active={!showTerms} onPress={() => router.replace('/legal' as any)} /><LegalTab label="Booking Terms" active={showTerms} onPress={() => router.replace('/legal?section=terms' as any)} /></View>{showTerms ? <TermsContent /> : <PrivacyContent />}</ScrollView></ScreenContainer>;
}

function LegalTab({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} className={active ? 'flex-1 rounded-xl bg-primary px-3 py-3' : 'flex-1 rounded-xl px-3 py-3'}><Text className={active ? 'text-center font-body text-xs font-extrabold text-white' : 'text-center font-body text-xs font-extrabold text-muted'}>{label}</Text></Pressable>; }

function PrivacyContent() { return <View className="mt-7"><Text className="font-body text-xs text-muted">Terakhir diperbarui: 18 Agustus 2026</Text><LegalSection title="Data yang kami kumpulkan" body="Saat kamu meminta informasi atau melanjutkan booking, Or.Trip dapat menerima nama, nomor telepon, email, detail peserta, pilihan trip, dan informasi yang diperlukan untuk administrasi perjalanan. Data identitas peserta harus digunakan hanya untuk keperluan perizinan dan operasional yang relevan." /><LegalSection title="Penggunaan data" body="Data digunakan untuk memproses booking, mengirim instruksi keberangkatan, melakukan briefing, menghubungi peserta terkait keselamatan, dan memberikan dukungan pelanggan. Or.Trip tidak menjual data pribadi kepada pihak lain." /><LegalSection title="Perlindungan dan retensi" body="Akses terhadap data booking dibatasi untuk kebutuhan operasional yang sah. Dokumen identitas tidak ditampilkan pada URL publik. Data disimpan selama diperlukan untuk administrasi, layanan pelanggan, kewajiban hukum, dan audit internal, lalu dihapus atau dianonimkan sesuai kebijakan retensi." /><LegalSection title="Berbagi data terbatas" body="Data dapat dibagikan secara terbatas kepada pihak yang membantu penyelenggaraan perjalanan, seperti pengelola kawasan, penyedia transportasi, asuransi, atau guide, hanya jika dibutuhkan untuk layanan dan keselamatan." /><LegalSection title="Hak peserta" body="Kamu dapat meminta informasi mengenai data yang tersimpan, meminta koreksi data, atau menghubungi tim Or.Trip melalui WhatsApp atau email resmi untuk pertanyaan privasi." /></View>; }

function TermsContent() { return <View className="mt-7"><Text className="font-body text-xs text-muted">Berlaku untuk booking Or.Trip Adventure</Text><LegalSection title="Pemesanan dan kuota" body="Booking dianggap diajukan setelah data peserta dan jadwal dipilih. Kuota, harga, dan status keberangkatan mengikuti informasi yang dikonfirmasi oleh admin. Or.Trip dapat meminta data tambahan untuk SIMAKSI atau kebutuhan operasional." /><LegalSection title="Pembayaran" body="Peserta membayar sesuai nominal dan batas waktu yang tercantum pada konfirmasi. Booking yang belum dibayar sesuai batas waktu dapat dibatalkan atau kedaluwarsa. Bukti pembayaran wajib disimpan sampai perjalanan selesai." /><LegalSection title="Perubahan dan pembatalan" body="Permintaan perubahan jadwal, peserta, meeting point, atau paket harus disampaikan secepatnya melalui kanal resmi. Persetujuan perubahan bergantung pada kuota, kebijakan operator, dan ketentuan kawasan. Detail refund atau reschedule dikonfirmasi pada saat booking." /><LegalSection title="Kesehatan dan keselamatan" body="Peserta wajib menyampaikan kondisi kesehatan yang relevan, mengikuti briefing, membawa perlengkapan wajib, mematuhi arahan guide, dan tidak memaksakan diri. Or.Trip dapat menghentikan atau menyesuaikan kegiatan apabila kondisi lapangan atau keselamatan mengharuskannya." /><LegalSection title="Perilaku dan lingkungan" body="Peserta wajib menghormati warga, guide, flora, fauna, peserta lain, serta menerapkan Leave No Trace. Pelanggaran aturan keselamatan atau kawasan dapat menyebabkan peserta dikeluarkan dari kegiatan tanpa menghilangkan kewajiban pembayaran yang telah disepakati." /></View>; }

function LegalSection({ title, body }: { title: string; body: string }) { return <View className="mt-6 rounded-2xl border border-border bg-surface p-4"><Text className="font-heading text-lg font-bold text-foreground">{title}</Text><Text className="mt-2 font-body text-sm leading-6 text-muted">{body}</Text></View>; }
