import { useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { PrimaryButton } from '@/components/trip-ui';
import { formatIDR, getTrip } from '@/lib/demo-data';

const methods = [{ id: 'qris', title: 'QRIS', body: 'Scan dari aplikasi bank atau e-wallet', icon: 'camera.fill' }, { id: 'transfer', title: 'Transfer bank', body: 'Mandiri · instruksi setelah konfirmasi', icon: 'arrow.right' }, { id: 'card', title: 'Kartu kredit', body: 'Visa, Mastercard, JCB', icon: 'checkmark.circle.fill' }];
export default function PaymentScreen() { const { tripId, participants } = useLocalSearchParams<{ tripId?: string; participants?: string }>(); const trip = getTrip(tripId); const count = Number(participants ?? 1); const [method, setMethod] = useState('qris'); const total = trip.price * count; return <ScreenContainer edges={['top', 'left', 'right', 'bottom']} className="bg-background" safeAreaClassName="bg-background"><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 40 }}><Pressable onPress={() => router.back()} className="mb-5 flex-row items-center"><IconSymbol name="arrow.left" size={18} color="#2D5A27" /><Text className="ml-2 font-body text-sm font-bold text-primary">Kembali</Text></Pressable><Text className="font-body text-xs font-bold uppercase tracking-widest text-primary">PEMBAYARAN</Text><Text className="mt-2 font-heading text-3xl font-bold text-foreground">Selesaikan booking.</Text><View className="mt-5 rounded-3xl bg-primary p-5"><Text className="font-body text-xs font-bold uppercase tracking-widest text-accent">TOTAL PEMBAYARAN</Text><Text className="mt-2 font-body text-3xl font-extrabold text-white">{formatIDR(total)}</Text><Text className="mt-1 font-body text-xs text-white/75">{trip.title} · {count} peserta</Text></View><Text className="mt-7 font-heading text-xl font-bold text-foreground">Pilih metode pembayaran</Text><View className="mt-3">{methods.map((item) => <Pressable key={item.id} onPress={() => setMethod(item.id)} className={`mb-3 flex-row items-center rounded-3xl border p-4 ${method === item.id ? 'border-primary bg-accent/30' : 'border-border bg-surface'}`}><View className={`h-11 w-11 items-center justify-center rounded-2xl ${method === item.id ? 'bg-primary' : 'bg-neutral'}`}><IconSymbol name={item.icon as any} size={20} color={method === item.id ? '#FFFFFF' : '#2D5A27'} /></View><View className="ml-3 flex-1"><Text className="font-body text-sm font-extrabold text-foreground">{item.title}</Text><Text className="mt-1 font-body text-xs text-muted">{item.body}</Text></View>{method === item.id ? <IconSymbol name="checkmark.circle.fill" size={21} color="#2D5A27" /> : null}</Pressable>)}</View><View className="mt-4 flex-row rounded-2xl bg-neutral p-4"><IconSymbol name="shield.fill" size={18} color="#2D5A27" /><Text className="ml-2 flex-1 font-body text-xs leading-5 text-muted">Pembayaran aman. Tim Or.Trip akan mengirim instruksi dan memvalidasi bukti pembayaran secara manual.</Text></View><View className="mt-6"><PrimaryButton label="Konfirmasi & dapatkan kode booking" onPress={() => router.push('/booking-success')} /></View></ScrollView></ScreenContainer>; }
