import { useState } from 'react';
import { router } from 'expo-router';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { Pill, PrimaryButton } from '@/components/trip-ui';

export default function PrivateTripScreen() { const [group, setGroup] = useState('4–7 orang'); return <ScreenContainer edges={['top', 'left', 'right', 'bottom']} className="bg-background" safeAreaClassName="bg-background"><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 40 }}><Pressable onPress={() => router.back()} className="mb-5 flex-row items-center"><IconSymbol name="arrow.left" size={18} color="#2D5A27" /><Text className="ml-2 font-body text-sm font-bold text-primary">Kembali</Text></Pressable><Text className="font-body text-xs font-bold uppercase tracking-widest text-primary">PRIVATE TRIP</Text><Text className="mt-2 font-heading text-3xl font-bold text-foreground">Rancang perjalananmu.</Text><Text className="mt-2 font-body text-sm leading-5 text-muted">Beritahu kami sedikit tentang grupmu. Tim kami akan bantu menyusun rute, ritme, dan detail yang paling pas.</Text><Field label="Destinasi impian" placeholder="Contoh: Rinjani, Ijen, Bromo" /><Field label="Tanggal atau range waktu" placeholder="Contoh: 12–14 Oktober 2026" /><Text className="mt-5 mb-2 font-body text-xs font-extrabold text-foreground">Jumlah peserta</Text><View className="flex-row"><Pill label="2–3 orang" active={group === '2–3 orang'} onPress={() => setGroup('2–3 orang')} /><Pill label="4–7 orang" active={group === '4–7 orang'} onPress={() => setGroup('4–7 orang')} /><Pill label="8+ orang" active={group === '8+ orang'} onPress={() => setGroup('8+ orang')} /></View><Field label="Kebutuhan khusus" placeholder="Aktivitas, penginapan, transport, budget..." multiline /><Field label="Kontak WhatsApp" placeholder="08xx-xxxx-xxxx" keyboardType="phone-pad" /><View className="mt-6"><PrimaryButton label="Kirim brief perjalanan" onPress={() => router.push('/booking-success?mode=private')} /></View></ScrollView></ScreenContainer>; }
function Field({ label, placeholder, multiline = false, keyboardType = 'default' }: { label: string; placeholder: string; multiline?: boolean; keyboardType?: any }) { return <View className="mt-5"><Text className="mb-2 font-body text-xs font-extrabold text-foreground">{label}</Text><TextInput placeholder={placeholder} placeholderTextColor="#8A978B" multiline={multiline} numberOfLines={multiline ? 4 : 1} keyboardType={keyboardType} className={`rounded-2xl border border-border bg-surface px-4 py-3.5 font-body text-sm text-foreground ${multiline ? 'min-h-[110px]' : ''}`} textAlignVertical={multiline ? 'top' : 'center'} /></View>; }
